
language: node_js
node_js:
  - 10.8.0

cache:
  directories:
    - "node_modules"

script:
  - yarn
  - yarn build

before_deploy:
- cd $TRAVIS_BUILD_DIR

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: build
    keep-history: true
    on:
      branch: master
