language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn build

branches:
  only:
    - gh-pages
    - develop

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  target_branch: master
  on:
    branch: gh-pages
